services:
  web1:
    image: nginx
    container_name: nginx-web1
    ports:
      - "8081:80"
    volumes:
      - ./site:/usr/share/nginx/html:ro
    restart: unless-stopped

  web2:
    image: nginx
    container_name: nginx-web2
    ports:
      - "8082:80"
    volumes:
      - ./site:/usr/share/nginx/html:ro
    restart: unless-stopped

  web3:
    image: nginx
    container_name: nginx-web3
    ports:
      - "8083:80"
    volumes:
      - ./site:/usr/share/nginx/html:ro
    restart: unless-stopped
